import Foundation

enum HangulData {
    static let all: [HangulLetter] = basicConsonants + basicVowels + doubleConsonants + compoundVowels

    static func letters(in category: HangulCategory) -> [HangulLetter] {
        all.filter { $0.category == category }
    }

    static let basicConsonants: [HangulLetter] = [
        HangulLetter(character: "ㄱ", romanization: "g / k", name: "기역 (giyeok)", category: .basicConsonant,
                     exampleWord: "가방", exampleRomanization: "gabang",
                     exampleMeaning: Bilingual(vi: "cái cặp", en: "bag")),
        HangulLetter(character: "ㄴ", romanization: "n", name: "니은 (nieun)", category: .basicConsonant,
                     exampleWord: "나무", exampleRomanization: "namu",
                     exampleMeaning: Bilingual(vi: "cái cây", en: "tree")),
        HangulLetter(character: "ㄷ", romanization: "d / t", name: "디귿 (digeut)", category: .basicConsonant,
                     exampleWord: "다리", exampleRomanization: "dari",
                     exampleMeaning: Bilingual(vi: "cái chân / cây cầu", en: "leg / bridge")),
        HangulLetter(character: "ㄹ", romanization: "r / l", name: "리을 (rieul)", category: .basicConsonant,
                     exampleWord: "라디오", exampleRomanization: "radio",
                     exampleMeaning: Bilingual(vi: "đài radio", en: "radio")),
        HangulLetter(character: "ㅁ", romanization: "m", name: "미음 (mieum)", category: .basicConsonant,
                     exampleWord: "머리", exampleRomanization: "meori",
                     exampleMeaning: Bilingual(vi: "cái đầu", en: "head")),
        HangulLetter(character: "ㅂ", romanization: "b / p", name: "비읍 (bieup)", category: .basicConsonant,
                     exampleWord: "바다", exampleRomanization: "bada",
                     exampleMeaning: Bilingual(vi: "biển", en: "sea")),
        HangulLetter(character: "ㅅ", romanization: "s", name: "시옷 (siot)", category: .basicConsonant,
                     exampleWord: "사람", exampleRomanization: "saram",
                     exampleMeaning: Bilingual(vi: "người", en: "person")),
        HangulLetter(character: "ㅇ", romanization: "ng / câm", name: "이응 (ieung)", category: .basicConsonant,
                     exampleWord: "아이", exampleRomanization: "ai",
                     exampleMeaning: Bilingual(vi: "đứa trẻ", en: "child")),
        HangulLetter(character: "ㅈ", romanization: "j", name: "지읒 (jieut)", category: .basicConsonant,
                     exampleWord: "자동차", exampleRomanization: "jadongcha",
                     exampleMeaning: Bilingual(vi: "xe hơi", en: "car")),
        HangulLetter(character: "ㅊ", romanization: "ch", name: "치읓 (chieut)", category: .basicConsonant,
                     exampleWord: "책", exampleRomanization: "chaek",
                     exampleMeaning: Bilingual(vi: "quyển sách", en: "book")),
        HangulLetter(character: "ㅋ", romanization: "k", name: "키읔 (kieuk)", category: .basicConsonant,
                     exampleWord: "코", exampleRomanization: "ko",
                     exampleMeaning: Bilingual(vi: "cái mũi", en: "nose")),
        HangulLetter(character: "ㅌ", romanization: "t", name: "티읕 (tieut)", category: .basicConsonant,
                     exampleWord: "토마토", exampleRomanization: "tomato",
                     exampleMeaning: Bilingual(vi: "cà chua", en: "tomato")),
        HangulLetter(character: "ㅍ", romanization: "p", name: "피읖 (pieup)", category: .basicConsonant,
                     exampleWord: "포도", exampleRomanization: "podo",
                     exampleMeaning: Bilingual(vi: "quả nho", en: "grape")),
        HangulLetter(character: "ㅎ", romanization: "h", name: "히읗 (hieut)", category: .basicConsonant,
                     exampleWord: "하늘", exampleRomanization: "haneul",
                     exampleMeaning: Bilingual(vi: "bầu trời", en: "sky")),
    ]

    static let basicVowels: [HangulLetter] = [
        HangulLetter(character: "ㅏ", romanization: "a", name: "아 (a)", category: .basicVowel,
                     exampleWord: "아빠", exampleRomanization: "appa",
                     exampleMeaning: Bilingual(vi: "bố", en: "dad")),
        HangulLetter(character: "ㅑ", romanization: "ya", name: "야 (ya)", category: .basicVowel,
                     exampleWord: "야구", exampleRomanization: "yagu",
                     exampleMeaning: Bilingual(vi: "bóng chày", en: "baseball")),
        HangulLetter(character: "ㅓ", romanization: "eo", name: "어 (eo)", category: .basicVowel,
                     exampleWord: "어머니", exampleRomanization: "eomeoni",
                     exampleMeaning: Bilingual(vi: "mẹ", en: "mother")),
        HangulLetter(character: "ㅕ", romanization: "yeo", name: "여 (yeo)", category: .basicVowel,
                     exampleWord: "여자", exampleRomanization: "yeoja",
                     exampleMeaning: Bilingual(vi: "phụ nữ", en: "woman")),
        HangulLetter(character: "ㅗ", romanization: "o", name: "오 (o)", category: .basicVowel,
                     exampleWord: "오리", exampleRomanization: "ori",
                     exampleMeaning: Bilingual(vi: "con vịt", en: "duck")),
        HangulLetter(character: "ㅛ", romanization: "yo", name: "요 (yo)", category: .basicVowel,
                     exampleWord: "요리", exampleRomanization: "yori",
                     exampleMeaning: Bilingual(vi: "nấu ăn", en: "cooking")),
        HangulLetter(character: "ㅜ", romanization: "u", name: "우 (u)", category: .basicVowel,
                     exampleWord: "우유", exampleRomanization: "uyu",
                     exampleMeaning: Bilingual(vi: "sữa", en: "milk")),
        HangulLetter(character: "ㅠ", romanization: "yu", name: "유 (yu)", category: .basicVowel,
                     exampleWord: "유리", exampleRomanization: "yuri",
                     exampleMeaning: Bilingual(vi: "thủy tinh", en: "glass")),
        HangulLetter(character: "ㅡ", romanization: "eu", name: "으 (eu)", category: .basicVowel,
                     exampleWord: "은행", exampleRomanization: "eunhaeng",
                     exampleMeaning: Bilingual(vi: "ngân hàng", en: "bank")),
        HangulLetter(character: "ㅣ", romanization: "i", name: "이 (i)", category: .basicVowel,
                     exampleWord: "이름", exampleRomanization: "ireum",
                     exampleMeaning: Bilingual(vi: "cái tên", en: "name")),
    ]

    static let doubleConsonants: [HangulLetter] = [
        HangulLetter(character: "ㄲ", romanization: "kk", name: "쌍기역 (ssanggiyeok)", category: .doubleConsonant,
                     exampleWord: "까치", exampleRomanization: "kkachi",
                     exampleMeaning: Bilingual(vi: "chim ác là", en: "magpie")),
        HangulLetter(character: "ㄸ", romanization: "tt", name: "쌍디귿 (ssangdigeut)", category: .doubleConsonant,
                     exampleWord: "딸기", exampleRomanization: "ttalgi",
                     exampleMeaning: Bilingual(vi: "dâu tây", en: "strawberry")),
        HangulLetter(character: "ㅃ", romanization: "pp", name: "쌍비읍 (ssangbieup)", category: .doubleConsonant,
                     exampleWord: "빵", exampleRomanization: "ppang",
                     exampleMeaning: Bilingual(vi: "bánh mì", en: "bread")),
        HangulLetter(character: "ㅆ", romanization: "ss", name: "쌍시옷 (ssangsiot)", category: .doubleConsonant,
                     exampleWord: "쌀", exampleRomanization: "ssal",
                     exampleMeaning: Bilingual(vi: "gạo", en: "uncooked rice")),
        HangulLetter(character: "ㅉ", romanization: "jj", name: "쌍지읒 (ssangjieut)", category: .doubleConsonant,
                     exampleWord: "짜다", exampleRomanization: "jjada",
                     exampleMeaning: Bilingual(vi: "mặn", en: "salty")),
    ]

    static let compoundVowels: [HangulLetter] = [
        HangulLetter(character: "ㅐ", romanization: "ae", name: "애 (ae)", category: .compoundVowel,
                     exampleWord: "개", exampleRomanization: "gae",
                     exampleMeaning: Bilingual(vi: "con chó", en: "dog")),
        HangulLetter(character: "ㅒ", romanization: "yae", name: "얘 (yae)", category: .compoundVowel,
                     exampleWord: "얘기", exampleRomanization: "yaegi",
                     exampleMeaning: Bilingual(vi: "câu chuyện", en: "talk")),
        HangulLetter(character: "ㅔ", romanization: "e", name: "에 (e)", category: .compoundVowel,
                     exampleWord: "게", exampleRomanization: "ge",
                     exampleMeaning: Bilingual(vi: "con cua", en: "crab")),
        HangulLetter(character: "ㅖ", romanization: "ye", name: "예 (ye)", category: .compoundVowel,
                     exampleWord: "예의", exampleRomanization: "yeui",
                     exampleMeaning: Bilingual(vi: "lễ nghi", en: "manners")),
        HangulLetter(character: "ㅘ", romanization: "wa", name: "와 (wa)", category: .compoundVowel,
                     exampleWord: "과일", exampleRomanization: "gwail",
                     exampleMeaning: Bilingual(vi: "trái cây", en: "fruit")),
        HangulLetter(character: "ㅙ", romanization: "wae", name: "왜 (wae)", category: .compoundVowel,
                     exampleWord: "왜", exampleRomanization: "wae",
                     exampleMeaning: Bilingual(vi: "tại sao", en: "why")),
        HangulLetter(character: "ㅚ", romanization: "oe", name: "외 (oe)", category: .compoundVowel,
                     exampleWord: "외국", exampleRomanization: "oeguk",
                     exampleMeaning: Bilingual(vi: "nước ngoài", en: "foreign country")),
        HangulLetter(character: "ㅝ", romanization: "wo", name: "워 (wo)", category: .compoundVowel,
                     exampleWord: "원숭이", exampleRomanization: "wonsungi",
                     exampleMeaning: Bilingual(vi: "con khỉ", en: "monkey")),
        HangulLetter(character: "ㅞ", romanization: "we", name: "웨 (we)", category: .compoundVowel,
                     exampleWord: "웨이터", exampleRomanization: "weiteo",
                     exampleMeaning: Bilingual(vi: "bồi bàn", en: "waiter")),
        HangulLetter(character: "ㅟ", romanization: "wi", name: "위 (wi)", category: .compoundVowel,
                     exampleWord: "가위", exampleRomanization: "gawi",
                     exampleMeaning: Bilingual(vi: "cái kéo", en: "scissors")),
        HangulLetter(character: "ㅢ", romanization: "ui", name: "의 (ui)", category: .compoundVowel,
                     exampleWord: "의사", exampleRomanization: "uisa",
                     exampleMeaning: Bilingual(vi: "bác sĩ", en: "doctor")),
    ]
}
